___

___
# GreenWood Project - Python Course:

## Course - Numpy Package
---

We will learn about Numpy library which stands for Numerical Python which is very fundamental and many other libraires are built on top of it.

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">


I. [Introduciton](#0)<br>
    II. [Numpy arrays](#1)<br>
    III. [Numpy Operations](#2)<br>
    IV. [Numpy Indexing and selection](#3)<br>
    V. [Famous methods](#4)<br>
    </div>

---
## I. Introduction <a id="0"></a>

Most of python environnements come with Numpy installed. Numpy is a numerical library for python that allows :

* For extremly fast data generation and handling.
* Uses arrays which can efficiently store data much better than python's data type list.

NUmpy is a very large library https://numpy.org/, we will only introduce here some numpy methods which will be relevant for our course.

In [3]:
import numpy as np

<div class="alert alert-block alert-success">
<b>Bear in mind:</b> Mastering numpy is an essential step before moving to pandas
</div>

## II. Numpy arrays <a id="1"></a>

Numpy arrays are :

* Vector : 1D list
* Matrix : 2D list or more

**Vector**

In [4]:
lst = [-1,-2,3]

In [5]:
arr = np.array(lst)
arr,type(arr)

(array([-1, -2,  3]), numpy.ndarray)

**Matrix**

In [7]:
mat = [[0,2,3],[1,3,-1],[0,1,-1],]
mat

[[0, 2, 3], [1, 3, -1], [0, 1, -1]]

In [9]:
np_mat = np.array(mat)
np_mat,type(np_mat)

(array([[ 0,  2,  3],
        [ 1,  3, -1],
        [ 0,  1, -1]]),
 numpy.ndarray)

**Get size of array**

In [41]:
np_mat.shape

(3, 3)

In [42]:
arr.shape

(3,)

**Convert 2D into 1D array**

In [47]:
np_mat.reshape(9)

array([ 0,  2,  3,  1,  3, -1,  0,  1, -1])

**np.arrange()**

same as range()

In [15]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**np.zeros()**

return array of zeros

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**np.ones()**

return array of ones

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

**np.linspace()**

returns an array of equi-distant floats in a specific range

np.linspace(0,10,10+1)

In [49]:
arr =np.linspace(0,5,10)

arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

**np.round**

rounds decimals of floats

In [51]:
arr.round(2)

array([0.  , 0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44, 5.  ])

**np.eye()**

returns digonal squared matrix

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<div class="alert alert-block alert-success">
<b>Bear in mind:</b> A numpy array will only contain numerical values
</div>

## III. Numpy Operations <a id="2"></a>

Let's apply arithmetic operations on a numpy arrays

In [78]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [79]:
3*arr

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [80]:
4-arr

array([ 4,  3,  2,  1,  0, -1, -2, -3])

In [81]:
arr2 = arr+10
arr2

array([10, 11, 12, 13, 14, 15, 16, 17])

In [82]:
arr + arr2

array([10, 12, 14, 16, 18, 20, 22, 24])

In [83]:
1/arr

<ipython-input-83-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714])

<div class="alert alert-block alert-danger">
<b>Just don't:</b> think you having an error while it is only a warning.
</div>

In [86]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [87]:
np.log(arr)

<ipython-input-87-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015])

In [89]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225])

<div class="alert alert-block alert-success">
<b>Bear in mind:</b> inf is reconized as a value
</div>

**Let's apply booleans operations on a numpy arrays**

In [134]:
np_mat

array([[ 0,  2,  3],
       [ 1,  3, -1],
       [ 0,  1, -1]])

In [135]:
np_mat > 0

array([[False,  True,  True],
       [ True,  True, False],
       [False,  True, False]])

In [136]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [137]:
arr < 5

array([ True,  True,  True,  True,  True, False, False, False])

## IV. Numpy Indexing and selecting <a id="3"></a>

Let's apply arithmetic operations on a numpy arrays

In [72]:
arr = [-1,2,0,3,11,5,7]

**Return max/min and relative indexes**

In [73]:
np.max(arr), np.min(arr)

(11, -1)

In [74]:
np.argmax(arr),np.argmin(arr)

(4, 0)

**Slicing and indexing**

In [94]:
arr[0]

0

In [97]:
arr[:3]

array([0, 1, 2])

In [105]:
arr[3:5]

array([3, 4])

In [107]:
arr[:-1:3] # not the same as list

array([0, 3, 6])

In [108]:
np_mat

array([[ 0,  2,  3],
       [ 1,  3, -1],
       [ 0,  1, -1]])

In [111]:
np_mat[0] # first row

array([0, 2, 3])

In [112]:
np_mat[1][:] # second row

array([ 1,  3, -1])

In [114]:
np_mat[2][1:] # slice of third row

array([ 1, -1])

## V. Famous Methods <a id="3"></a>

**np.random**

Module containing multiple distributions

In [93]:
# random integers between low and high
np.random.randint(0,10,11)

array([6, 5, 4, 4, 5, 9, 8, 8, 5, 5, 1])

In [91]:
# uniform distribution
np.random.rand(5,5)

array([[0.20809012, 0.93362653, 0.86285123, 0.59130426, 0.47869089],
       [0.51315313, 0.40568639, 0.37636058, 0.67345478, 0.78745014],
       [0.39501013, 0.77321624, 0.52519656, 0.3684033 , 0.72085125],
       [0.91941912, 0.47916736, 0.11072391, 0.83578592, 0.03461051],
       [0.94723952, 0.01446474, 0.8698862 , 0.32853884, 0.72656972]])

In [92]:
# standard normal distribution
np.random.rand(5,5)

array([[0.55585726, 0.66676253, 0.74787066, 0.63664811, 0.92186997],
       [0.20357506, 0.54649829, 0.78740024, 0.45961164, 0.06071514],
       [0.90630059, 0.21341381, 0.09652317, 0.3135393 , 0.96973875],
       [0.24693435, 0.40997077, 0.12697695, 0.81075463, 0.06105359],
       [0.32131437, 0.96857879, 0.78082259, 0.07912393, 0.88337029]])

In [119]:
np_mat

array([[ 0,  2,  3],
       [ 1,  3, -1],
       [ 0,  1, -1]])

In [123]:
np_mat.dtype # type of elements inside matrix

dtype('int64')

In [125]:
np.abs(np_mat) # abs values

array([[0, 2, 3],
       [1, 3, 1],
       [0, 1, 1]])

In [127]:
np_mat.astype('float') # convert int values into float

array([[ 0.,  2.,  3.],
       [ 1.,  3., -1.],
       [ 0.,  1., -1.]])

<div class="alert alert-block alert-danger">
<b>Just don't:</b> Use numpy for unordered data types or strings.
</div>

## III. Practises <a id="2"></a>

**Creat an array of 20 zeros**

**Creat an array of 10 fives**

**Get length of previous list**

**Generate a random number between 0 and 1**

In [167]:
np.random.random(1)

array([0.32883441])

In [166]:
np.random.ranf(1) #continuous uniform” distribution

array([0.36268739])

# Great Job!