___

___
# GreenWood Project - Python Course:

## Exercices + Solutions - Numpy library
---

In [2]:
import numpy as np

## Exercise 1

Creating a 1D Array

In [3]:
np.array([2,3,4,0])

array([2, 3, 4, 0])

## Exercise 2

Create a 2D array

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Exercise 3

1. Get second row of our array
2. Get Slice of array starting third row
3. Get max of matrix
4. Get second element of third row
5. Calculate sum of elements
6. convert array into 1D

In [5]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

**1. Get second row of our array**

**2. Get Slice of array starting third row**

In [6]:
arr[1]

array([ 4. , -0.5,  6. ,  0. ])

In [7]:
arr[2:]

array([[ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

**3. Get max of matrix**

In [12]:
arr.max()

8.0

**4. Get second element of third row**

In [13]:
arr[2][2]

7.0

**5. Calculate sum of elements**

In [15]:
arr.sum()

34.1

In [23]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

**6. convert array into 1D**

In [25]:
arr.reshape(4*4)

array([-1. ,  2. ,  0. ,  4. ,  4. , -0.5,  6. ,  0. ,  2.6,  0. ,  7. ,
        8. ,  3. , -7. ,  4. ,  2. ])

## Exercise 4

1. Build an adequate data type you link currencies to rates

    Each element of rates corresponds to a currency in order.
    
    
2. Calculate mean of rates of each currency and add to your data type.


3. Build a 2D matrix from rates values

In [84]:
rates = [[1,0.81,0.95,0.92],[1.23,1,1.11,.97],[1.05,1.08,1,0.84],[0.90,1.03,1.19,1]]

target = ['CAD','NZD','USD','AUD']

In [88]:
d = dict()
for key,val in zip(target,rates):
    d[key]=  np.array(val)
d

{'CAD': array([1.  , 0.81, 0.95, 0.92]),
 'NZD': array([1.23, 1.  , 1.11, 0.97]),
 'USD': array([1.05, 1.08, 1.  , 0.84]),
 'AUD': array([0.9 , 1.03, 1.19, 1.  ])}

**2. Calculate mean of rates of each currency and add to your data type.**

In [89]:
d['Means'] = np.empty(0,dtype=float)

In [93]:
for vals in list(d.values())[:-1]:
    print(np.mean(vals))
    d['Means'] = np.append(d['Means'],np.mean(vals))

0.9199999999999999
1.0775
0.9924999999999999
1.03


In [94]:
d

{'CAD': array([1.  , 0.81, 0.95, 0.92]),
 'NZD': array([1.23, 1.  , 1.11, 0.97]),
 'USD': array([1.05, 1.08, 1.  , 0.84]),
 'AUD': array([0.9 , 1.03, 1.19, 1.  ]),
 'Means': array([0.92  , 1.0775, 0.9925, 1.03  , 0.92  , 1.0775, 0.9925, 1.03  ])}

**3. Build a 2D matrix from rates values**

In [95]:
mat = np.array(rates)
mat

array([[1.  , 0.81, 0.95, 0.92],
       [1.23, 1.  , 1.11, 0.97],
       [1.05, 1.08, 1.  , 0.84],
       [0.9 , 1.03, 1.19, 1.  ]])

# Great Job!